# Задание:
#
# Возьмите исходники простейшего PHP-приложения.
# Добавьте docker-compose.yml конфигурацию с двумя сервисами: php и nginx.
# Nginx должен использовать готовый докер-образ, сервис php должен собираться из текущей директории. Для этого в репозитории есть Dockerfile.
# Добавьте healthcheck для php-сервиса, который ходил бы на http://nginx и проверял содержимое на наличие строки «works» (это можно сделать через curl и grep).
# Запустить приложение через Docker Compose.
# Результатом проверки будет скриншот из браузера по доступному приложению на http://127.0.0.1:80/ и содержимое docker-compose.yml.

services:

  nginx:
    image: nginx
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./www:/var/www"
    ports:
      - "127.0.0.1:80:80"
    networks:
      - net
    links:
      - php

  php:
    build: .
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://nginx | grep -c works > /dev/null"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "./www:/var/www"
    networks:
      - net

networks:
  net:

  
