version: "3.9"

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "1000m"
   max-file: "1"

services:
  web:
    build: .
    ports:
      - "127.0.0.1:${WEB_PORT}:5000"
    depends_on:
     redis:
        condition: service_healthy
    networks:
      - net
    logging: *logging

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    networks:
      - net
    logging: *logging
    profiles:
      - redis
    deploy:
     resources:
       limits:
         cpus: "${DOCKER_WEB_CPUS:-0}"
         memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

networks:
  net:

volumes:
  redis-data:
