FROM alpine:latest as builder
WORKDIR /opt/

FROM scratch
COPY --from=builder /lib/ld-musl-aarch64.so.1 /lib/
COPY --from=builder /bin/sh /bin/busybox /usr/bin/wget /usr/bin/ssl_client /bin/
COPY --from=builder /usr/lib/libssl.so.3 /usr/lib/libcrypto.so.3 /lib/
COPY ./fav_downloader.sh /opt/
#ENTRYPOINT ["/opt/fav_downloader.sh"]



# 	linux-vdso.so.1 (0x0000ffff9e194000)
#	libtinfo.so.6 => /lib/aarch64-linux-gnu/libtinfo.so.6 (0x0000ffff9df70000)
#	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff9ddb0000)
#	/lib/ld-linux-aarch64.so.1 (0x0000ffff9e157000)
#
#   libpcre2-8.so.0 => /lib/aarch64-linux-gnu/libpcre2-8.so.0 (0x0000ffffb55b0000)
#	libuuid.so.1 => /lib/aarch64-linux-gnu/libuuid.so.1 (0x0000ffffb5580000)
#	libidn2.so.0 => /lib/aarch64-linux-gnu/libidn2.so.0 (0x0000ffffb5540000)
#	libssl.so.3 => /lib/aarch64-linux-gnu/libssl.so.3 (0x0000ffffb5470000)
#	libcrypto.so.3 => /lib/aarch64-linux-gnu/libcrypto.so.3 (0x0000ffffb4ff0000)
#	libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000ffffb4fb0000)
#	libpsl.so.5 => /lib/aarch64-linux-gnu/libpsl.so.5 (0x0000ffffb4f70000)
#	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffb4db0000)
#	/lib/ld-linux-aarch64.so.1 (0x0000ffffb56f3000)
#	libunistring.so.5 => /lib/aarch64-linux-gnu/libunistring.so.5 (0x0000ffffb4be0000)

#/lib/ld-musl-aarch64.so.1 (0xffffbae58000)
#libc.musl-aarch64.so.1 => /lib/ld-musl-aarch64.so.1 (0xffffbae58000)

#